Update /manifests with default cluster profile annotation
operator-framework/operator-lifecycle-manager pull request #1887
Opened 2020-12-03 16:20 UTC by guillaumerose

Updated with `make release`

2020-12-03 16:22 UTC, kevinrizza requested changes

2020-12-03 16:22 UTC, kevinrizza commented on manifests/0000_50_olm_07-olm-operator.deployment.yaml
> +            - --namespace
Seems like there's a lot of churn on spacing here? Can we avoid that?

2020-12-03 16:22 UTC, kevinrizza commented on manifests/0000_50_olm_00-operatorgroups.crd.yaml
> -  - name: v1
This also seems like a lot of churn

2020-12-03 16:22 UTC, kevinrizza commented
/ok-to-test

2020-12-10 20:18 UTC, guillaumerose commented
/retest

2020-12-10 20:22 UTC, kevinrizza commented
/lgtm
/approve

2020-12-11 19:27 UTC, kevinrizza commented
/retest

2020-12-14 12:16 UTC, guillaumerose commented
/bugzilla refresh

2020-12-14 19:20 UTC, dinhxuanvu commented
/retest

2020-12-14 19:22 UTC, guillaumerose commented
GH actions are green, thanks! Now, we need the openshift CI 🙏

2020-12-15 01:08 UTC, eparis commented
```
pods/openshift-cluster-version_cluster-version-operator-54bb4c667c-kncbw_cluster-version-operator.log.gz:E1214 22:16:36.916095       1 runtime.go:78] Observed a panic: &errors.errorString{s:"v1.ClusterOperator.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ability\":true},\"name|..., bigger context ...|ase.openshift.io/self-managed-high-availability\":true},\"name\":\"operator-lifecycle-manager\"},\"status\"|..."} (v1.ClusterOperator.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|ability":true},"name|..., bigger context ...|ase.openshift.io/self-managed-high-availability":true},"name":"operator-lifecycle-manager"},"status"|...)
```

It is because you are trying to set `true` instead of `"true"` so it's being treated as a boolean, not as a string, and it can't parse correctly?

2020-12-15 01:09 UTC, eparis commented
/hold
no need to keep wasting CI cycles trying to parse a bool as a strong. feel free to unhold when you get CI fixed

2020-12-15 08:38 UTC, guillaumerose commented
I added the double quote. Let's see how it goes now. Thanks @eparis for spotting the error!

2020-12-15 12:19 UTC, guillaumerose commented
/retest

2020-12-15 13:00 UTC, guillaumerose commented
/retest

2020-12-15 13:18 UTC, kevinrizza commented
/test e2e-aws-olm

2020-12-15 13:18 UTC, kevinrizza commented
/lgtm
/hold cancel

2020-12-15 19:23 UTC, eparis commented
/retest

2020-12-16 16:33 UTC, guillaumerose commented
/hold

CI is in trouble right now.

2020-12-17 08:40 UTC, guillaumerose commented
/retest

2020-12-18 16:24 UTC, guillaumerose commented
/retest

2020-12-18 19:10 UTC, dinhxuanvu commented
@guillaumerose There are a few e2e test cases that are failing consistently. Can you run those test locally to see they are passing or not?

2020-12-20 18:58 UTC, guillaumerose commented
@dinhxuanvu these failures are the same I observed in others PRs. For example, https://github.com/operator-framework/operator-lifecycle-manager/pull/1913

2020-12-23 13:38 UTC, guillaumerose commented
/retest

2020-12-23 16:08 UTC, guillaumerose commented
/retest

2020-12-23 20:13 UTC, guillaumerose commented
All green! Thanks @awgreene for fixing the CI.

2021-01-04 12:28 UTC, ecordell commented
/hold cancel

2021-01-04 12:32 UTC, ecordell commented
/lgtm

2021-01-04 13:16 UTC, kevinrizza commented
/test e2e-aws-console-olm

2021-01-04 16:13 UTC, merged