Use amd64 for local linux builds
operator-framework/operator-lifecycle-manager pull request #1944
Opened 2021-01-07 16:29 UTC by ecordell

32 bit arches hit a golang bug:
https://github.com/kubernetes/kubernetes/issues/97685

**Description of the change:**
Changes local linux builds (for kind/etc) to use amd64 instead of 386

**Motivation for the change:**
Avoid https://github.com/kubernetes/kubernetes/issues/97685

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage 
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/docs` 
- [ ] Commit messages sensible and descriptive

2021-01-07 16:46 UTC, exdx commented
/lgtm

2021-01-07 16:49 UTC, dinhxuanvu approved these changes
/lgtm

2021-01-07 16:50 UTC, dinhxuanvu commented
Do we need a BZ to merge this or can we merge this manually?

2021-01-07 17:55 UTC, dinhxuanvu approved these changes
/lgtm

2021-01-07 17:57 UTC, dinhxuanvu requested changes
Just a small typo.

2021-01-07 17:57 UTC, dinhxuanvu commented on x.mk
> +test/e2e-local.image.tar: export GOARCH=amd4
Typo: `amd64`

2021-01-07 18:01 UTC, dinhxuanvu approved these changes
/lgtm

2021-01-13 14:49 UTC, benluddy commented
/hold

Pausing bot spam until someone is able to look at the failing checks.

2021-02-15 16:48 UTC, dinhxuanvu commented
/retest

2021-03-30 12:56 UTC, closed without merging