Handles incorrect CatalogSource interval values.
operator-framework/operator-lifecycle-manager pull request #2294
Opened 2021-07-27 18:52 UTC by DhritiShikhar

**Description of the change:**

Handles incorrect CatalogSource interval values.

Example:

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-operator-catalog 
  publisher: IBM Content
  sourceType: grpc
  image: docker.io/ibmcom/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45mError code    ################### incorrect value
```

Note:
Changes to `vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go` should be removed. 
The correct location of the code with tests is in this PR -> https://github.com/operator-framework/api/pull/142

**Reviewer Checklist**
- [x] Implementation matches the proposed design, or proposal is updated to match implementation
- [x] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive

2021-07-28 03:12 UTC, DhritiShikhar commented
/hold 

Made changes to the UpdateStrategy unmarshal inside the vendor folder for reviews. Actual PR is here -> https://github.com/operator-framework/api/pull/142

will unhold once this and the api repo PR is lgtmed and changes from api is vendored in here.

2021-07-29 13:03 UTC, anik120 requested changes
Thanks for the PR @DhritiShikhar 🎉 

An e2e here as proof of concept would be nice too.

Also, what you think of the following design: 

In `catalogsource_types.go` we change the `RegistryPoll` struct to include a new field
```
type RegistryPoll struct {
	ParsingError error                                                               // new field
	Interval *metav1.Duration `json:"interval,omitempty"`        // existing field
}
```

so that we can set that field if there is any error while unmarshalling:

```
func (u *UpdateStrategy) UnmarshalJSON(b []byte) error {

	var data map[string]map[string]string
	err := json.Unmarshal(b, &data)

	registryPoll := &RegistryPoll{}
	pd, err := time.ParseDuration(data["registryPoll"]["interval"])
	if err != nil {
		registryPoll.ParsingError = fmt.Errorf("error parsing spec.updateStrategy.registryPoll.interval. Setting the default value of %v. Error:%v", DefaultRegistryPollDuration, err)
		defaultTime, _ := time.ParseDuration(DefaultRegistryPollDuration)
		registryPoll.Interval = &metav1.Duration{defaultTime}
	} else {
		registryPoll.ParsingError = nil
		registryPoll.Interval = &metav1.Duration{pd}
	}
	u.RegistryPoll = registryPoll
	return nil
}
```

That we can use here to 1. log the error 2. set a condition in the catsrc, so that the user is aware why the value that they put, eg `20 minutes` got turned into `15m`: 
```
if out.Spec.UpdateStrategy != nil {
		if out.Spec.UpdateStrategy.RegistryPoll.ParsingError != nil {
			// set catsrc.status.conditions to let user know there was a problem, i.e explain why a default value is being used.
		}
		logger.Debugf("requeuing registry server sync based on polling interval %s", out.Spec.UpdateStrategy.Interval.Duration.String())
		resyncPeriod := reconciler.SyncRegistryUpdateInterval(out, time.Now())
		o.catsrcQueueSet.RequeueAfter(out.GetNamespace(), out.GetName(), queueinformer.ResyncWithJitter(resyncPeriod, 0.1)())
		return
	}
```

2021-07-29 13:04 UTC, anik120 commented
/ok-to-test

2021-08-30 12:34 UTC, DhritiShikhar commented on pkg/controller/operators/catalog/operator.go
> +					return
```
	if out.Spec.UpdateStrategy != nil {
		if out.Spec.UpdateStrategy.RegistryPoll != nil {
```

The updateStrategy may not be nil but RegistryPoll may be nil, that's why added an extra check for the same.

Without this, we see an error.

2021-08-30 12:39 UTC, DhritiShikhar commented on pkg/controller/operators/catalog/operator.go
> +					return
We parse the duration, we set the correct value to out.Spec.UpdateStrategy.RegistryPoll.Interval but this line is needed to write it back to the original CatalogSource.

2021-08-30 13:13 UTC, DhritiShikhar commented
@anik120 

- Added `ParsingError` field and updated the CatalogSource status as per your suggestion

2021-08-30 17:45 UTC, dinhxuanvu commented
@DhritiShikhar Did you test this locally? I have a feeling that this will not work (hopefully I'm wrong). The reason is because this invalid interval value will break the informer so it will fail before it even reaches the check code that you add.

2021-08-31 15:29 UTC, DhritiShikhar commented
@dinhxuanvu Yes, tested this locally.

If the interval value is invalid, it's caught during the Unmarshalling and changed to default value -> https://github.com/operator-framework/api/pull/142

2021-09-09 19:25 UTC, anik120 commented
PR's looking to be in a good place. The API PR is failing the CI though, so if we can solve those errors, get that merged, and then vendor those changes in here, this PR should be ready to go in.

2021-11-12 22:46 UTC, anik120 commented
/close in favor of #2447

2021-11-12 22:46 UTC, closed without merging