Return copy of annotations in grpcCatalogSourceDecorator
operator-framework/operator-lifecycle-manager pull request #2813
Opened 2022-07-07 11:05 UTC by perdasilva

Signed-off-by: perdasilva <perdasilva@redhat.com>

**Description of the change:**
Recent changes adding the grpcCatalogSourceDecorator introduced a concurrent write issue on the annotations. This PR updates the Annotations method to return a copy of the annotations to avoid this issue.

**Motivation for the change:**
https://bugzilla.redhat.com/show_bug.cgi?id=2101357

**Architectural changes:**
None

**Testing remarks:**
Deployed on kind and not seeing the issue

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

2022-07-07 13:05 UTC, awgreene approved these changes
Alternatively, we could generate the list of annotations once when creating the grpcCatalogSourceDecorator, but I don't think this will introduce a huge performance impact.

2022-07-07 13:25 UTC, timflannagan approved these changes
+1 on Alex's suggestion as well. Looking through the rest of these methods, it looks like we wouldn't have the same issue as labels. Do we need a test here?

2022-07-07 13:58 UTC, perdasilva commented
> +1 on Alex's suggestion as well. Looking through the rest of these methods, it looks like we wouldn't have the same issue as labels. Do we need a test here?

I was trying to think how to add one, but wasn't sure the best way to test it. I'm also wondering if we should move the logic to the reconciler.

2022-07-07 14:36 UTC, awgreene commented
I think this is a small enough change that I'm comfortable merging as is.

2022-07-07 15:48 UTC, timflannagan commented
Yep, same here, and it's definitely helpful that you linked to the BZ so we're tracking some historical context over time.

2022-07-08 12:43 UTC, awgreene commented on pkg/controller/registry/reconciler/reconciler_test.go
> +		"annotation": "somethignelse",
```suggestion
		"annotation": "somethingelse",
```

2022-07-08 12:43 UTC, awgreene commented on pkg/controller/registry/reconciler/reconciler_test.go
> +		"annotation": "somethignelse",
I also prefer camelCase.

2022-07-08 12:48 UTC, awgreene requested changes
Found one spelling mistake, otherwise looks good.

2022-07-08 13:28 UTC, perdasilva commented
> Found one spelling mistake, otherwise looks good.

Fixed!! good eyes =D

2022-07-08 13:35 UTC, timflannagan commented
/lgtm

2022-07-11 18:45 UTC, awgreene reviewed
Another option is to add a comment stating that the `reconcile.Pod function` will mutate the labels/annotations provided and updating all calls to provide copies, but making the function copy the arrays is probably safer for future developers that might rely on this method.

/lgtm

2022-07-11 19:59 UTC, awgreene commented
/approve

2022-07-11 19:59 UTC, awgreene approved these changes

2022-07-11 20:05 UTC, merged