Fix update installplan status conflict
operator-framework/operator-lifecycle-manager pull request #2838
Opened 2022-08-13 03:44 UTC by aiyijing

Signed-off-by: aiyijing <aiyijing@live.com>

**Description of the change:**
Fix update installplan status conflict.
**Motivation for the change:**
Empty installplan will cause the Subscription status to block in UpgradePending
**Architectural changes:**

**Testing remarks:**

**Reviewer Checklist**
- [ ] Implementation matches the proposed design, or proposal is updated to match implementation
- [ ] Sufficient unit test coverage
- [ ] Sufficient end-to-end test coverage
- [ ] Bug fixes are accompanied by regression test(s)
- [ ] e2e tests and flake fixes are accompanied evidence of flake testing, e.g. executing the test 100(0) times
- [ ] tech debt/todo is accompanied by issue link(s) in comments in the surrounding code
- [ ] Tests are comprehensible, e.g. Ginkgo DSL is being used appropriately
- [ ] Docs updated or added to `/doc`
- [ ] Commit messages sensible and descriptive
- [ ] Tests marked as `[FLAKE]` are truly flaky and have an issue
- [ ] Code is properly formatted

Close https://github.com/operator-framework/operator-lifecycle-manager/issues/2795

2022-08-13 03:50 UTC, aiyijing commented
/assign @exdx

2022-08-13 13:54 UTC, timflannagan commented
/ok-to-test

2022-08-17 20:38 UTC, dinhxuanvu commented
The PR looks good but need to correct/investigate the unit test failure.

2023-02-28 09:49 UTC, perdasilva commented
@aiyijing can you please rebase?

2023-07-17 09:13 UTC, perdasilva requested changes
Please remote isSupported and its structures, or use it somewhere

2023-07-17 09:13 UTC, perdasilva commented on pkg/controller/operators/catalog/operator.go
> +const (
These don't seem to be used anywhere. Needed?

2024-02-19 13:30 UTC, perdasilva commented
closing PR as stale. Please re-open if it's still important.

2024-02-19 13:30 UTC, closed without merging